version: "2.3"

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
        networks: 
            - java_network    
    redis:
        container_name: redis
        image: redis:latest
        ports: 
            - 6379:6739
        networks: 
            - java_network
    java-docker:
        container_name: java-docker
        image: java-dokcer:1.0
        ports: 
            - 8080:8080
        depends_on: 
            - redis
            - mongo
        environment: 
            - NAME=Docker
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - REDIS_HOST=6379
        networks: 
            - java_network

networks: 
    java_network:
        name: java_network
